// EDIT IT, change to your package, service and message

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: extension/aop/dynamic_plugin/api/ioc_golang/aop/dynamic_plugin/dynamic_plugin.proto

package dynamic_plugin

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DynamicPluginUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sdid         string `protobuf:"bytes,1,opt,name=sdid,proto3" json:"sdid,omitempty"`
	AutowireType string `protobuf:"bytes,2,opt,name=autowireType,proto3" json:"autowireType,omitempty"`
	PluginFile   []byte `protobuf:"bytes,3,opt,name=pluginFile,proto3" json:"pluginFile,omitempty"`
	PluginName   string `protobuf:"bytes,4,opt,name=pluginName,proto3" json:"pluginName,omitempty"`
}

func (x *DynamicPluginUpdateRequest) Reset() {
	*x = DynamicPluginUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DynamicPluginUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicPluginUpdateRequest) ProtoMessage() {}

func (x *DynamicPluginUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicPluginUpdateRequest.ProtoReflect.Descriptor instead.
func (*DynamicPluginUpdateRequest) Descriptor() ([]byte, []int) {
	return file_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *DynamicPluginUpdateRequest) GetSdid() string {
	if x != nil {
		return x.Sdid
	}
	return ""
}

func (x *DynamicPluginUpdateRequest) GetAutowireType() string {
	if x != nil {
		return x.AutowireType
	}
	return ""
}

func (x *DynamicPluginUpdateRequest) GetPluginFile() []byte {
	if x != nil {
		return x.PluginFile
	}
	return nil
}

func (x *DynamicPluginUpdateRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

type DynamicPluginUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DynamicPluginUpdateResponse) Reset() {
	*x = DynamicPluginUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DynamicPluginUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicPluginUpdateResponse) ProtoMessage() {}

func (x *DynamicPluginUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicPluginUpdateResponse.ProtoReflect.Descriptor instead.
func (*DynamicPluginUpdateResponse) Descriptor() ([]byte, []int) {
	return file_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *DynamicPluginUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DynamicPluginUpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto protoreflect.FileDescriptor

var file_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto_rawDesc = []byte{
	0x0a, 0x53, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x61, 0x6f, 0x70, 0x2f,
	0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x69, 0x6f, 0x63, 0x5f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x61, 0x6f,
	0x70, 0x2f, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x2f, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x69, 0x6f, 0x63, 0x5f, 0x67, 0x6f, 0x6c, 0x61, 0x6e,
	0x67, 0x2e, 0x61, 0x6f, 0x70, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x5f, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x22, 0x94, 0x01, 0x0a, 0x1a, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63,
	0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x73, 0x64, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x75, 0x74, 0x6f, 0x77,
	0x69, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61,
	0x75, 0x74, 0x6f, 0x77, 0x69, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0a, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x51, 0x0a, 0x1b, 0x44,
	0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x9a,
	0x01, 0x0a, 0x14, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x81, 0x01, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x39, 0x2e, 0x69, 0x6f, 0x63, 0x5f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e,
	0x61, 0x6f, 0x70, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x5f, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x2e, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3a, 0x2e,
	0x69, 0x6f, 0x63, 0x5f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x61, 0x6f, 0x70, 0x2e, 0x64,
	0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x44, 0x79,
	0x6e, 0x61, 0x6d, 0x69, 0x63, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1f, 0x5a, 0x1d, 0x69,
	0x6f, 0x63, 0x5f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x61, 0x6f, 0x70, 0x2f, 0x64, 0x79,
	0x6e, 0x61, 0x6d, 0x69, 0x63, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto_rawDescOnce sync.Once
	file_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto_rawDescData = file_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto_rawDesc
)

func file_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto_rawDescGZIP() []byte {
	file_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto_rawDescOnce.Do(func() {
		file_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(file_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto_rawDescData)
	})
	return file_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto_rawDescData
}

var file_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto_goTypes = []interface{}{
	(*DynamicPluginUpdateRequest)(nil),  // 0: ioc_golang.aop.dynamic_plugin.DynamicPluginUpdateRequest
	(*DynamicPluginUpdateResponse)(nil), // 1: ioc_golang.aop.dynamic_plugin.DynamicPluginUpdateResponse
}
var file_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto_depIdxs = []int32{
	0, // 0: ioc_golang.aop.dynamic_plugin.DynamicPluginService.Update:input_type -> ioc_golang.aop.dynamic_plugin.DynamicPluginUpdateRequest
	1, // 1: ioc_golang.aop.dynamic_plugin.DynamicPluginService.Update:output_type -> ioc_golang.aop.dynamic_plugin.DynamicPluginUpdateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() {
	file_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto_init()
}
func file_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto_init() {
	if File_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DynamicPluginUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DynamicPluginUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto_goTypes,
		DependencyIndexes: file_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto_depIdxs,
		MessageInfos:      file_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto_msgTypes,
	}.Build()
	File_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto = out.File
	file_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto_rawDesc = nil
	file_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto_goTypes = nil
	file_extension_aop_dynamic_plugin_api_ioc_golang_aop_dynamic_plugin_dynamic_plugin_proto_depIdxs = nil
}
