// EDIT IT, change to your package, service and message

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: extension/aop/call/api/ioc_golang/aop/call/call.proto

package call

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sdid         string   `protobuf:"bytes,1,opt,name=sdid,proto3" json:"sdid,omitempty"`
	MethodName   string   `protobuf:"bytes,2,opt,name=methodName,proto3" json:"methodName,omitempty"`
	AutowireType string   `protobuf:"bytes,3,opt,name=autowireType,proto3" json:"autowireType,omitempty"`
	Params       []string `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty"`
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extension_aop_call_api_ioc_golang_aop_call_call_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_aop_call_api_ioc_golang_aop_call_call_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_extension_aop_call_api_ioc_golang_aop_call_call_proto_rawDescGZIP(), []int{0}
}

func (x *CallRequest) GetSdid() string {
	if x != nil {
		return x.Sdid
	}
	return ""
}

func (x *CallRequest) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *CallRequest) GetAutowireType() string {
	if x != nil {
		return x.AutowireType
	}
	return ""
}

func (x *CallRequest) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

type CallResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sdid         string   `protobuf:"bytes,1,opt,name=sdid,proto3" json:"sdid,omitempty"`
	MethodName   string   `protobuf:"bytes,2,opt,name=methodName,proto3" json:"methodName,omitempty"`
	Params       []string `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
	ReturnValues []string `protobuf:"bytes,4,rep,name=returnValues,proto3" json:"returnValues,omitempty"`
}

func (x *CallResponse) Reset() {
	*x = CallResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extension_aop_call_api_ioc_golang_aop_call_call_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse) ProtoMessage() {}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extension_aop_call_api_ioc_golang_aop_call_call_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse.ProtoReflect.Descriptor instead.
func (*CallResponse) Descriptor() ([]byte, []int) {
	return file_extension_aop_call_api_ioc_golang_aop_call_call_proto_rawDescGZIP(), []int{1}
}

func (x *CallResponse) GetSdid() string {
	if x != nil {
		return x.Sdid
	}
	return ""
}

func (x *CallResponse) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *CallResponse) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *CallResponse) GetReturnValues() []string {
	if x != nil {
		return x.ReturnValues
	}
	return nil
}

var File_extension_aop_call_api_ioc_golang_aop_call_call_proto protoreflect.FileDescriptor

var file_extension_aop_call_api_ioc_golang_aop_call_call_proto_rawDesc = []byte{
	0x0a, 0x35, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x61, 0x6f, 0x70, 0x2f,
	0x63, 0x61, 0x6c, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x6f, 0x63, 0x5f, 0x67, 0x6f, 0x6c,
	0x61, 0x6e, 0x67, 0x2f, 0x61, 0x6f, 0x70, 0x2f, 0x63, 0x61, 0x6c, 0x6c, 0x2f, 0x63, 0x61, 0x6c,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x69, 0x6f, 0x63, 0x5f, 0x67, 0x6f, 0x6c,
	0x61, 0x6e, 0x67, 0x2e, 0x61, 0x6f, 0x70, 0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x22, 0x7d, 0x0a, 0x0b,
	0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x64, 0x69, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x22, 0x0a, 0x0c, 0x61, 0x75, 0x74, 0x6f, 0x77, 0x69, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x75, 0x74, 0x6f, 0x77, 0x69, 0x72, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x7e, 0x0a, 0x0c, 0x43,
	0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x64, 0x69, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x72,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x32, 0x5c, 0x0a, 0x0b, 0x43,
	0x61, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a, 0x04, 0x43, 0x61,
	0x6c, 0x6c, 0x12, 0x20, 0x2e, 0x69, 0x6f, 0x63, 0x5f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e,
	0x61, 0x6f, 0x70, 0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x69, 0x6f, 0x63, 0x5f, 0x67, 0x6f, 0x6c, 0x61, 0x6e,
	0x67, 0x2e, 0x61, 0x6f, 0x70, 0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13, 0x69, 0x6f, 0x63,
	0x5f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x61, 0x6f, 0x70, 0x2f, 0x63, 0x61, 0x6c, 0x6c,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_extension_aop_call_api_ioc_golang_aop_call_call_proto_rawDescOnce sync.Once
	file_extension_aop_call_api_ioc_golang_aop_call_call_proto_rawDescData = file_extension_aop_call_api_ioc_golang_aop_call_call_proto_rawDesc
)

func file_extension_aop_call_api_ioc_golang_aop_call_call_proto_rawDescGZIP() []byte {
	file_extension_aop_call_api_ioc_golang_aop_call_call_proto_rawDescOnce.Do(func() {
		file_extension_aop_call_api_ioc_golang_aop_call_call_proto_rawDescData = protoimpl.X.CompressGZIP(file_extension_aop_call_api_ioc_golang_aop_call_call_proto_rawDescData)
	})
	return file_extension_aop_call_api_ioc_golang_aop_call_call_proto_rawDescData
}

var file_extension_aop_call_api_ioc_golang_aop_call_call_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_extension_aop_call_api_ioc_golang_aop_call_call_proto_goTypes = []interface{}{
	(*CallRequest)(nil),  // 0: ioc_golang.aop.call.CallRequest
	(*CallResponse)(nil), // 1: ioc_golang.aop.call.CallResponse
}
var file_extension_aop_call_api_ioc_golang_aop_call_call_proto_depIdxs = []int32{
	0, // 0: ioc_golang.aop.call.CallService.Call:input_type -> ioc_golang.aop.call.CallRequest
	1, // 1: ioc_golang.aop.call.CallService.Call:output_type -> ioc_golang.aop.call.CallResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_extension_aop_call_api_ioc_golang_aop_call_call_proto_init() }
func file_extension_aop_call_api_ioc_golang_aop_call_call_proto_init() {
	if File_extension_aop_call_api_ioc_golang_aop_call_call_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_extension_aop_call_api_ioc_golang_aop_call_call_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extension_aop_call_api_ioc_golang_aop_call_call_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_extension_aop_call_api_ioc_golang_aop_call_call_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_extension_aop_call_api_ioc_golang_aop_call_call_proto_goTypes,
		DependencyIndexes: file_extension_aop_call_api_ioc_golang_aop_call_call_proto_depIdxs,
		MessageInfos:      file_extension_aop_call_api_ioc_golang_aop_call_call_proto_msgTypes,
	}.Build()
	File_extension_aop_call_api_ioc_golang_aop_call_call_proto = out.File
	file_extension_aop_call_api_ioc_golang_aop_call_call_proto_rawDesc = nil
	file_extension_aop_call_api_ioc_golang_aop_call_call_proto_goTypes = nil
	file_extension_aop_call_api_ioc_golang_aop_call_call_proto_depIdxs = nil
}
