//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by iocli, run 'iocli gen' to re-generate

package impl

import (
	autowire "github.com/alibaba/ioc-golang/autowire"
	service "github.com/alibaba/ioc-golang/example/autowire/autowire_allimpls/service"
	allimpls "github.com/alibaba/ioc-golang/extension/autowire/allimpls"
)

func init() {
	serviceImpl1StructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &serviceImpl1{}
		},
		Metadata: map[string]interface{}{
			"autowire": map[string]interface{}{
				"allimpls": []interface{}{
					new(service.Service),
				},
			},
		},
		DisableProxy: true,
	}
	allimpls.RegisterStructDescriptor(serviceImpl1StructDescriptor)
	serviceImpl2StructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &serviceImpl2{}
		},
		Metadata: map[string]interface{}{
			"autowire": map[string]interface{}{
				"allimpls": []interface{}{
					new(service.Service),
				},
			},
		},
		DisableProxy: true,
	}
	allimpls.RegisterStructDescriptor(serviceImpl2StructDescriptor)
}

var _serviceImpl1SDID string
var _serviceImpl2SDID string
