// EDIT IT, change to your package, service and message

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: extension/aop/monitor/api/ioc_golang/aop/monitor/monitor.proto

package monitor

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MonitorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sdid     string `protobuf:"bytes,1,opt,name=sdid,proto3" json:"sdid,omitempty"`
	Method   string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Interval int64  `protobuf:"varint,3,opt,name=interval,proto3" json:"interval,omitempty"`
}

func (x *MonitorRequest) Reset() {
	*x = MonitorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MonitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorRequest) ProtoMessage() {}

func (x *MonitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorRequest.ProtoReflect.Descriptor instead.
func (*MonitorRequest) Descriptor() ([]byte, []int) {
	return file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *MonitorRequest) GetSdid() string {
	if x != nil {
		return x.Sdid
	}
	return ""
}

func (x *MonitorRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *MonitorRequest) GetInterval() int64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

type MonitorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MonitorResponseItems []*MonitorResponseItem `protobuf:"bytes,1,rep,name=monitorResponseItems,proto3" json:"monitorResponseItems,omitempty"`
}

func (x *MonitorResponse) Reset() {
	*x = MonitorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MonitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorResponse) ProtoMessage() {}

func (x *MonitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorResponse.ProtoReflect.Descriptor instead.
func (*MonitorResponse) Descriptor() ([]byte, []int) {
	return file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *MonitorResponse) GetMonitorResponseItems() []*MonitorResponseItem {
	if x != nil {
		return x.MonitorResponseItems
	}
	return nil
}

type MonitorResponseItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64   `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sdid      string  `protobuf:"bytes,2,opt,name=sdid,proto3" json:"sdid,omitempty"`
	Method    string  `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Total     int64   `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Success   int64   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	Fail      int64   `protobuf:"varint,6,opt,name=fail,proto3" json:"fail,omitempty"`
	AvgRT     float32 `protobuf:"fixed32,7,opt,name=avgRT,proto3" json:"avgRT,omitempty"`
	FailRate  float32 `protobuf:"fixed32,8,opt,name=failRate,proto3" json:"failRate,omitempty"`
}

func (x *MonitorResponseItem) Reset() {
	*x = MonitorResponseItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MonitorResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorResponseItem) ProtoMessage() {}

func (x *MonitorResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorResponseItem.ProtoReflect.Descriptor instead.
func (*MonitorResponseItem) Descriptor() ([]byte, []int) {
	return file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_rawDescGZIP(), []int{2}
}

func (x *MonitorResponseItem) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MonitorResponseItem) GetSdid() string {
	if x != nil {
		return x.Sdid
	}
	return ""
}

func (x *MonitorResponseItem) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *MonitorResponseItem) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MonitorResponseItem) GetSuccess() int64 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *MonitorResponseItem) GetFail() int64 {
	if x != nil {
		return x.Fail
	}
	return 0
}

func (x *MonitorResponseItem) GetAvgRT() float32 {
	if x != nil {
		return x.AvgRT
	}
	return 0
}

func (x *MonitorResponseItem) GetFailRate() float32 {
	if x != nil {
		return x.FailRate
	}
	return 0
}

var File_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto protoreflect.FileDescriptor

var file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_rawDesc = []byte{
	0x0a, 0x3e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x61, 0x6f, 0x70, 0x2f,
	0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x6f, 0x63, 0x5f,
	0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x61, 0x6f, 0x70, 0x2f, 0x6d, 0x6f, 0x6e, 0x69, 0x74,
	0x6f, 0x72, 0x2f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x16, 0x69, 0x6f, 0x63, 0x5f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x61, 0x6f, 0x70,
	0x2e, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x22, 0x58, 0x0a, 0x0e, 0x4d, 0x6f, 0x6e, 0x69,
	0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x64,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x64, 0x69, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76,
	0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76,
	0x61, 0x6c, 0x22, 0x72, 0x0a, 0x0f, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5f, 0x0a, 0x14, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x69, 0x6f, 0x63, 0x5f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67,
	0x2e, 0x61, 0x6f, 0x70, 0x2e, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x4d, 0x6f, 0x6e,
	0x69, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x14, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0xd5, 0x01, 0x0a, 0x13, 0x4d, 0x6f, 0x6e, 0x69, 0x74,
	0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x64, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x64, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x61, 0x69, 0x6c,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05,
	0x61, 0x76, 0x67, 0x52, 0x54, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x61, 0x76, 0x67,
	0x52, 0x54, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x61, 0x69, 0x6c, 0x52, 0x61, 0x74, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x66, 0x61, 0x69, 0x6c, 0x52, 0x61, 0x74, 0x65, 0x32, 0x70,
	0x0a, 0x0e, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x5e, 0x0a, 0x07, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x12, 0x26, 0x2e, 0x69, 0x6f,
	0x63, 0x5f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x61, 0x6f, 0x70, 0x2e, 0x6d, 0x6f, 0x6e,
	0x69, 0x74, 0x6f, 0x72, 0x2e, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x69, 0x6f, 0x63, 0x5f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67,
	0x2e, 0x61, 0x6f, 0x70, 0x2e, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x4d, 0x6f, 0x6e,
	0x69, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01,
	0x42, 0x18, 0x5a, 0x16, 0x69, 0x6f, 0x63, 0x5f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x61,
	0x6f, 0x70, 0x2f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_rawDescOnce sync.Once
	file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_rawDescData = file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_rawDesc
)

func file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_rawDescGZIP() []byte {
	file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_rawDescOnce.Do(func() {
		file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_rawDescData)
	})
	return file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_rawDescData
}

var file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_goTypes = []interface{}{
	(*MonitorRequest)(nil),      // 0: ioc_golang.aop.monitor.MonitorRequest
	(*MonitorResponse)(nil),     // 1: ioc_golang.aop.monitor.MonitorResponse
	(*MonitorResponseItem)(nil), // 2: ioc_golang.aop.monitor.MonitorResponseItem
}
var file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_depIdxs = []int32{
	2, // 0: ioc_golang.aop.monitor.MonitorResponse.monitorResponseItems:type_name -> ioc_golang.aop.monitor.MonitorResponseItem
	0, // 1: ioc_golang.aop.monitor.MonitorService.Monitor:input_type -> ioc_golang.aop.monitor.MonitorRequest
	1, // 2: ioc_golang.aop.monitor.MonitorService.Monitor:output_type -> ioc_golang.aop.monitor.MonitorResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_init() }
func file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_init() {
	if File_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MonitorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MonitorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MonitorResponseItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_goTypes,
		DependencyIndexes: file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_depIdxs,
		MessageInfos:      file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_msgTypes,
	}.Build()
	File_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto = out.File
	file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_rawDesc = nil
	file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_goTypes = nil
	file_extension_aop_monitor_api_ioc_golang_aop_monitor_monitor_proto_depIdxs = nil
}
