//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by iocli, run 'iocli gen' to re-generate

package service

import (
	autowire "github.com/alibaba/ioc-golang/autowire"
	normal "github.com/alibaba/ioc-golang/autowire/normal"
	allimpls "github.com/alibaba/ioc-golang/extension/autowire/allimpls"
)

func init() {
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &serviceImpl3_{}
		},
	})
	serviceImpl3StructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &serviceImpl3{}
		},
		Metadata: map[string]interface{}{
			"aop": map[string]interface{}{},
			"autowire": map[string]interface{}{
				"common": map[string]interface{}{
					"implements": []interface{}{
						new(Service),
					},
				},
			},
		},
	}
	allimpls.RegisterStructDescriptor(serviceImpl3StructDescriptor)
	var _ Service = &serviceImpl3{}
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &serviceImpl4_{}
		},
	})
	serviceImpl4StructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &serviceImpl4{}
		},
		Metadata: map[string]interface{}{
			"aop": map[string]interface{}{},
			"autowire": map[string]interface{}{
				"common": map[string]interface{}{
					"implements": []interface{}{
						new(Service),
					},
				},
			},
		},
	}
	allimpls.RegisterStructDescriptor(serviceImpl4StructDescriptor)
	var _ Service = &serviceImpl4{}
}

type serviceImpl3_ struct {
	GetHelloString_ func(name string) string
}

func (s *serviceImpl3_) GetHelloString(name string) string {
	return s.GetHelloString_(name)
}

type serviceImpl4_ struct {
	GetHelloString_ func(name string) string
}

func (s *serviceImpl4_) GetHelloString(name string) string {
	return s.GetHelloString_(name)
}

type serviceImpl3IOCInterface interface {
	GetHelloString(name string) string
}

type serviceImpl4IOCInterface interface {
	GetHelloString(name string) string
}

var _serviceImpl3SDID string
var _serviceImpl4SDID string
