//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by iocli, run 'iocli gen' to re-generate

package aop

import (
	testingx "testing"

	ioc_golangaop "github.com/alibaba/ioc-golang/aop"
	autowire "github.com/alibaba/ioc-golang/autowire"
	normal "github.com/alibaba/ioc-golang/autowire/normal"
	"github.com/alibaba/ioc-golang/autowire/singleton"
	"github.com/alibaba/ioc-golang/autowire/util"
)

func init() {
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &normalApp_{}
		},
	})
	normalAppStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &NormalApp{}
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
	}
	normal.RegisterStructDescriptor(normalAppStructDescriptor)
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &afterIsCalledAfterPanicTestInterceptor_{}
		},
	})
	afterIsCalledAfterPanicTestInterceptorStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &afterIsCalledAfterPanicTestInterceptor{}
		},
		ConstructFunc: func(i interface{}, _ interface{}) (interface{}, error) {
			impl := i.(*afterIsCalledAfterPanicTestInterceptor)
			var constructFunc afterIsCalledAfterPanicTestInterceptorConstructFunc = initAfterIsCalledAfterPanicTestInterceptor
			return constructFunc(impl)
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
	}
	singleton.RegisterStructDescriptor(afterIsCalledAfterPanicTestInterceptorStructDescriptor)
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &panicAfterCalledTestSubApp_{}
		},
	})
	panicAfterCalledTestSubAppStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &PanicAfterCalledTestSubApp{}
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
	}
	singleton.RegisterStructDescriptor(panicAfterCalledTestSubAppStructDescriptor)
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &panicAfterCalledTestApp_{}
		},
	})
	panicAfterCalledTestAppStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &PanicAfterCalledTestApp{}
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
	}
	singleton.RegisterStructDescriptor(panicAfterCalledTestAppStructDescriptor)
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &recursiveApp_{}
		},
	})
	recursiveAppStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &RecursiveApp{}
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
	}
	singleton.RegisterStructDescriptor(recursiveAppStructDescriptor)
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &serviceImpl1_{}
		},
	})
	serviceImpl1StructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &ServiceImpl1{}
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
	}
	singleton.RegisterStructDescriptor(serviceImpl1StructDescriptor)
	normal.RegisterStructDescriptor(serviceImpl1StructDescriptor)
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &serviceImpl2_{}
		},
	})
	serviceImpl2StructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &ServiceImpl2{}
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
	}
	singleton.RegisterStructDescriptor(serviceImpl2StructDescriptor)
	normal.RegisterStructDescriptor(serviceImpl2StructDescriptor)
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &serviceStruct_{}
		},
	})
	serviceStructStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &ServiceStruct{}
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
	}
	singleton.RegisterStructDescriptor(serviceStructStructDescriptor)
	normal.RegisterStructDescriptor(serviceStructStructDescriptor)
}

type afterIsCalledAfterPanicTestInterceptorConstructFunc func(impl *afterIsCalledAfterPanicTestInterceptor) (*afterIsCalledAfterPanicTestInterceptor, error)
type normalApp_ struct {
	RunTest_ func(t *testingx.T)
}

func (n *normalApp_) RunTest(t *testingx.T) {
	n.RunTest_(t)
}

type afterIsCalledAfterPanicTestInterceptor_ struct {
	GetAfterIsCalledNum_ func() int
	BeforeInvoke_        func(ctx *ioc_golangaop.InvocationContext)
	AfterInvoke_         func(ctx *ioc_golangaop.InvocationContext)
}

func (a *afterIsCalledAfterPanicTestInterceptor_) GetAfterIsCalledNum() int {
	return a.GetAfterIsCalledNum_()
}

func (a *afterIsCalledAfterPanicTestInterceptor_) BeforeInvoke(ctx *ioc_golangaop.InvocationContext) {
	a.BeforeInvoke_(ctx)
}

func (a *afterIsCalledAfterPanicTestInterceptor_) AfterInvoke(ctx *ioc_golangaop.InvocationContext) {
	a.AfterInvoke_(ctx)
}

type panicAfterCalledTestSubApp_ struct {
	RunWithPanic_ func(panicMsg string)
}

func (p *panicAfterCalledTestSubApp_) RunWithPanic(panicMsg string) {
	p.RunWithPanic_(panicMsg)
}

type panicAfterCalledTestApp_ struct {
	RunWithPanic_ func(panicMst string) (result string)
}

func (p *panicAfterCalledTestApp_) RunWithPanic(panicMst string) (result string) {
	return p.RunWithPanic_(panicMst)
}

type recursiveApp_ struct {
	Reset_   func()
	RunTest_ func(t *testingx.T)
}

func (r *recursiveApp_) Reset() {
	r.Reset_()
}

func (r *recursiveApp_) RunTest(t *testingx.T) {
	r.RunTest_(t)
}

type serviceImpl1_ struct {
	GetHelloString_ func(name string) string
}

func (s *serviceImpl1_) GetHelloString(name string) string {
	return s.GetHelloString_(name)
}

type serviceImpl2_ struct {
	GetHelloString_ func(name string) string
}

func (s *serviceImpl2_) GetHelloString(name string) string {
	return s.GetHelloString_(name)
}

type serviceStruct_ struct {
	GetString_ func(name string) string
}

func (s *serviceStruct_) GetString(name string) string {
	return s.GetString_(name)
}

type NormalAppIOCInterface interface {
	RunTest(t *testingx.T)
}

type afterIsCalledAfterPanicTestInterceptorIOCInterface interface {
	GetAfterIsCalledNum() int
	BeforeInvoke(ctx *ioc_golangaop.InvocationContext)
	AfterInvoke(ctx *ioc_golangaop.InvocationContext)
}

type PanicAfterCalledTestSubAppIOCInterface interface {
	RunWithPanic(panicMsg string)
}

type PanicAfterCalledTestAppIOCInterface interface {
	RunWithPanic(panicMst string) (result string)
}

type RecursiveAppIOCInterface interface {
	Reset()
	RunTest(t *testingx.T)
}

type ServiceImpl1IOCInterface interface {
	GetHelloString(name string) string
}

type ServiceImpl2IOCInterface interface {
	GetHelloString(name string) string
}

type ServiceStructIOCInterface interface {
	GetString(name string) string
}

var _normalAppSDID string

func GetNormalApp() (*NormalApp, error) {
	if _normalAppSDID == "" {
		_normalAppSDID = util.GetSDIDByStructPtr(new(NormalApp))
	}
	i, err := normal.GetImpl(_normalAppSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*NormalApp)
	return impl, nil
}

func GetNormalAppIOCInterface() (NormalAppIOCInterface, error) {
	if _normalAppSDID == "" {
		_normalAppSDID = util.GetSDIDByStructPtr(new(NormalApp))
	}
	i, err := normal.GetImplWithProxy(_normalAppSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(NormalAppIOCInterface)
	return impl, nil
}

var _afterIsCalledAfterPanicTestInterceptorSDID string

func GetafterIsCalledAfterPanicTestInterceptorSingleton() (*afterIsCalledAfterPanicTestInterceptor, error) {
	if _afterIsCalledAfterPanicTestInterceptorSDID == "" {
		_afterIsCalledAfterPanicTestInterceptorSDID = util.GetSDIDByStructPtr(new(afterIsCalledAfterPanicTestInterceptor))
	}
	i, err := singleton.GetImpl(_afterIsCalledAfterPanicTestInterceptorSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*afterIsCalledAfterPanicTestInterceptor)
	return impl, nil
}

func GetafterIsCalledAfterPanicTestInterceptorIOCInterfaceSingleton() (afterIsCalledAfterPanicTestInterceptorIOCInterface, error) {
	if _afterIsCalledAfterPanicTestInterceptorSDID == "" {
		_afterIsCalledAfterPanicTestInterceptorSDID = util.GetSDIDByStructPtr(new(afterIsCalledAfterPanicTestInterceptor))
	}
	i, err := singleton.GetImplWithProxy(_afterIsCalledAfterPanicTestInterceptorSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(afterIsCalledAfterPanicTestInterceptorIOCInterface)
	return impl, nil
}

var _panicAfterCalledTestSubAppSDID string

func GetPanicAfterCalledTestSubAppSingleton() (*PanicAfterCalledTestSubApp, error) {
	if _panicAfterCalledTestSubAppSDID == "" {
		_panicAfterCalledTestSubAppSDID = util.GetSDIDByStructPtr(new(PanicAfterCalledTestSubApp))
	}
	i, err := singleton.GetImpl(_panicAfterCalledTestSubAppSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*PanicAfterCalledTestSubApp)
	return impl, nil
}

func GetPanicAfterCalledTestSubAppIOCInterfaceSingleton() (PanicAfterCalledTestSubAppIOCInterface, error) {
	if _panicAfterCalledTestSubAppSDID == "" {
		_panicAfterCalledTestSubAppSDID = util.GetSDIDByStructPtr(new(PanicAfterCalledTestSubApp))
	}
	i, err := singleton.GetImplWithProxy(_panicAfterCalledTestSubAppSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(PanicAfterCalledTestSubAppIOCInterface)
	return impl, nil
}

var _panicAfterCalledTestAppSDID string

func GetPanicAfterCalledTestAppSingleton() (*PanicAfterCalledTestApp, error) {
	if _panicAfterCalledTestAppSDID == "" {
		_panicAfterCalledTestAppSDID = util.GetSDIDByStructPtr(new(PanicAfterCalledTestApp))
	}
	i, err := singleton.GetImpl(_panicAfterCalledTestAppSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*PanicAfterCalledTestApp)
	return impl, nil
}

func GetPanicAfterCalledTestAppIOCInterfaceSingleton() (PanicAfterCalledTestAppIOCInterface, error) {
	if _panicAfterCalledTestAppSDID == "" {
		_panicAfterCalledTestAppSDID = util.GetSDIDByStructPtr(new(PanicAfterCalledTestApp))
	}
	i, err := singleton.GetImplWithProxy(_panicAfterCalledTestAppSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(PanicAfterCalledTestAppIOCInterface)
	return impl, nil
}

var _recursiveAppSDID string

func GetRecursiveAppSingleton() (*RecursiveApp, error) {
	if _recursiveAppSDID == "" {
		_recursiveAppSDID = util.GetSDIDByStructPtr(new(RecursiveApp))
	}
	i, err := singleton.GetImpl(_recursiveAppSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*RecursiveApp)
	return impl, nil
}

func GetRecursiveAppIOCInterfaceSingleton() (RecursiveAppIOCInterface, error) {
	if _recursiveAppSDID == "" {
		_recursiveAppSDID = util.GetSDIDByStructPtr(new(RecursiveApp))
	}
	i, err := singleton.GetImplWithProxy(_recursiveAppSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(RecursiveAppIOCInterface)
	return impl, nil
}

var _serviceImpl1SDID string

func GetServiceImpl1Singleton() (*ServiceImpl1, error) {
	if _serviceImpl1SDID == "" {
		_serviceImpl1SDID = util.GetSDIDByStructPtr(new(ServiceImpl1))
	}
	i, err := singleton.GetImpl(_serviceImpl1SDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*ServiceImpl1)
	return impl, nil
}

func GetServiceImpl1IOCInterfaceSingleton() (ServiceImpl1IOCInterface, error) {
	if _serviceImpl1SDID == "" {
		_serviceImpl1SDID = util.GetSDIDByStructPtr(new(ServiceImpl1))
	}
	i, err := singleton.GetImplWithProxy(_serviceImpl1SDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(ServiceImpl1IOCInterface)
	return impl, nil
}

func GetServiceImpl1() (*ServiceImpl1, error) {
	if _serviceImpl1SDID == "" {
		_serviceImpl1SDID = util.GetSDIDByStructPtr(new(ServiceImpl1))
	}
	i, err := normal.GetImpl(_serviceImpl1SDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*ServiceImpl1)
	return impl, nil
}

func GetServiceImpl1IOCInterface() (ServiceImpl1IOCInterface, error) {
	if _serviceImpl1SDID == "" {
		_serviceImpl1SDID = util.GetSDIDByStructPtr(new(ServiceImpl1))
	}
	i, err := normal.GetImplWithProxy(_serviceImpl1SDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(ServiceImpl1IOCInterface)
	return impl, nil
}

var _serviceImpl2SDID string

func GetServiceImpl2Singleton() (*ServiceImpl2, error) {
	if _serviceImpl2SDID == "" {
		_serviceImpl2SDID = util.GetSDIDByStructPtr(new(ServiceImpl2))
	}
	i, err := singleton.GetImpl(_serviceImpl2SDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*ServiceImpl2)
	return impl, nil
}

func GetServiceImpl2IOCInterfaceSingleton() (ServiceImpl2IOCInterface, error) {
	if _serviceImpl2SDID == "" {
		_serviceImpl2SDID = util.GetSDIDByStructPtr(new(ServiceImpl2))
	}
	i, err := singleton.GetImplWithProxy(_serviceImpl2SDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(ServiceImpl2IOCInterface)
	return impl, nil
}

func GetServiceImpl2() (*ServiceImpl2, error) {
	if _serviceImpl2SDID == "" {
		_serviceImpl2SDID = util.GetSDIDByStructPtr(new(ServiceImpl2))
	}
	i, err := normal.GetImpl(_serviceImpl2SDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*ServiceImpl2)
	return impl, nil
}

func GetServiceImpl2IOCInterface() (ServiceImpl2IOCInterface, error) {
	if _serviceImpl2SDID == "" {
		_serviceImpl2SDID = util.GetSDIDByStructPtr(new(ServiceImpl2))
	}
	i, err := normal.GetImplWithProxy(_serviceImpl2SDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(ServiceImpl2IOCInterface)
	return impl, nil
}

var _serviceStructSDID string

func GetServiceStructSingleton() (*ServiceStruct, error) {
	if _serviceStructSDID == "" {
		_serviceStructSDID = util.GetSDIDByStructPtr(new(ServiceStruct))
	}
	i, err := singleton.GetImpl(_serviceStructSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*ServiceStruct)
	return impl, nil
}

func GetServiceStructIOCInterfaceSingleton() (ServiceStructIOCInterface, error) {
	if _serviceStructSDID == "" {
		_serviceStructSDID = util.GetSDIDByStructPtr(new(ServiceStruct))
	}
	i, err := singleton.GetImplWithProxy(_serviceStructSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(ServiceStructIOCInterface)
	return impl, nil
}

func GetServiceStruct() (*ServiceStruct, error) {
	if _serviceStructSDID == "" {
		_serviceStructSDID = util.GetSDIDByStructPtr(new(ServiceStruct))
	}
	i, err := normal.GetImpl(_serviceStructSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*ServiceStruct)
	return impl, nil
}

func GetServiceStructIOCInterface() (ServiceStructIOCInterface, error) {
	if _serviceStructSDID == "" {
		_serviceStructSDID = util.GetSDIDByStructPtr(new(ServiceStruct))
	}
	i, err := normal.GetImplWithProxy(_serviceStructSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(ServiceStructIOCInterface)
	return impl, nil
}
