//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by iocli, run 'iocli gen' to re-generate

package cli

import (
	autowire "github.com/alibaba/ioc-golang/autowire"
	allimpls "github.com/alibaba/ioc-golang/extension/autowire/allimpls"
	marker "github.com/alibaba/ioc-golang/iocli/gen/marker"
)

func init() {
	transactionFunctionMarkerStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &transactionFunctionMarker{}
		},
		Metadata: map[string]interface{}{
			"autowire": map[string]interface{}{
				"allimpls": []interface{}{
					new(marker.DefinitionGetter),
				},
			},
		},
		DisableProxy: true,
	}
	allimpls.RegisterStructDescriptor(transactionFunctionMarkerStructDescriptor)
}

var _transactionFunctionMarkerSDID string
