//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by iocli, run 'iocli gen' to re-generate

package list

import (
	autowire "github.com/alibaba/ioc-golang/autowire"
	singleton "github.com/alibaba/ioc-golang/autowire/singleton"
	util "github.com/alibaba/ioc-golang/autowire/util"
)

func init() {
	listServiceImplStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &listServiceImpl{}
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
		DisableProxy: true,
	}
	singleton.RegisterStructDescriptor(listServiceImplStructDescriptor)
}

var _listServiceImplSDID string

func GetlistServiceImplSingleton() (*listServiceImpl, error) {
	if _listServiceImplSDID == "" {
		_listServiceImplSDID = util.GetSDIDByStructPtr(new(listServiceImpl))
	}
	i, err := singleton.GetImpl(_listServiceImplSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*listServiceImpl)
	return impl, nil
}
