// Code generated by mockery v2.12.2. DO NOT EDIT.

/*
 * Copyright (c) 2022, Alibaba Group;
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package autowire

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// MockAutowire is an autogenerated mock type for the MockAutowire type
type MockAutowire struct {
	mock.Mock
}

// CanBeEntrance provides a mock function with given fields:
func (_m *MockAutowire) CanBeEntrance() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Construct provides a mock function with given fields: sdID, impledPtr, param
func (_m *MockAutowire) Construct(sdID string, impledPtr interface{}, param interface{}) (interface{}, error) {
	ret := _m.Called(sdID, impledPtr, param)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(string, interface{}, interface{}) interface{}); ok {
		r0 = rf(sdID, impledPtr, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, interface{}, interface{}) error); ok {
		r1 = rf(sdID, impledPtr, param)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Factory provides a mock function with given fields: sdID
func (_m *MockAutowire) Factory(sdID string) (interface{}, error) {
	ret := _m.Called(sdID)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = rf(sdID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(sdID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllStructDescribers provides a mock function with given fields:
func (_m *MockAutowire) GetAllStructDescribers() map[string]*StructDescriber {
	ret := _m.Called()

	var r0 map[string]*StructDescriber
	if rf, ok := ret.Get(0).(func() map[string]*StructDescriber); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*StructDescriber)
		}
	}

	return r0
}

// InjectPosition provides a mock function with given fields:
func (_m *MockAutowire) InjectPosition() InjectPosition {
	ret := _m.Called()

	var r0 InjectPosition
	if rf, ok := ret.Get(0).(func() InjectPosition); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(InjectPosition)
	}

	return r0
}

// IsSingleton provides a mock function with given fields:
func (_m *MockAutowire) IsSingleton() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ParseParam provides a mock function with given fields: sdID, fi
func (_m *MockAutowire) ParseParam(sdID string, fi *FieldInfo) (interface{}, error) {
	ret := _m.Called(sdID, fi)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(string, *FieldInfo) interface{}); ok {
		r0 = rf(sdID, fi)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, *FieldInfo) error); ok {
		r1 = rf(sdID, fi)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParseSDID provides a mock function with given fields: field
func (_m *MockAutowire) ParseSDID(field *FieldInfo) (string, error) {
	ret := _m.Called(field)

	var r0 string
	if rf, ok := ret.Get(0).(func(*FieldInfo) string); ok {
		r0 = rf(field)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*FieldInfo) error); ok {
		r1 = rf(field)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TagKey provides a mock function with given fields:
func (_m *MockAutowire) TagKey() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewMockAutowire creates a new instance of MockAutowire. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockAutowire(t testing.TB) *MockAutowire {
	mock := &MockAutowire{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
