//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by ioc-go-cli

package service2

import (
	autowire "github.com/alibaba/ioc-golang/autowire"
	singleton "github.com/alibaba/ioc-golang/autowire/singleton"
)

func init() {
	singleton.RegisterStructDescriber(&autowire.StructDescriber{
		Interface: new(Service2),
		Factory: func() interface{} {
			return &Impl1{}
		},
	})
	singleton.RegisterStructDescriber(&autowire.StructDescriber{
		Interface: new(Service2),
		Factory: func() interface{} {
			return &Impl2{}
		},
	})
}
