// Code generated by iocli

package api

import (
	"github.com/alibaba/ioc-golang/autowire"
	"github.com/alibaba/ioc-golang/example/autowire_rpc/server/pkg/dto"
	"github.com/alibaba/ioc-golang/extension/autowire/rpc/rpc_client"
)

func init() {
	rpc_client.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &ServiceStructIOCRPCClient{}
		},
	})
}

type ServiceStructIOCRPCClient struct {
	GetUser func(name string, age int, age32 int32, age64 int64, ageF32 float32, ageF64 float64, agePtr *int, age32Ptr *int32, age64Ptr *int64, ageF32Ptr *float32, ageF64Ptr *float64, reqUsr *dto.User) (*dto.User, *dto.User, error)
}
