// Code generated by iocli

package api

import (
	"github.com/alibaba/ioc-golang/autowire"
	"github.com/alibaba/ioc-golang/example/autowire_rpc/server/pkg/dto"
	"github.com/alibaba/ioc-golang/extension/autowire/rpc/rpc_client"
)

func init() {
	rpc_client.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &ServiceStructIOCRPCClient{}
		},
	})
}

type ServiceStructIOCRPCClient struct {
	GetUser func(name string, age int) (*dto.User, error)
}
