//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by ioc-go-cli

package struct1

import (
	autowire "github.com/alibaba/IOC-Golang/autowire"
	singleton "github.com/alibaba/IOC-Golang/autowire/singleton"
)

func init() {
	singleton.RegisterStructDescriber(&autowire.StructDescriber{
		Interface: &Struct1{},
		Factory: func() interface{} {
			return &Struct1{}
		},
	})
}
