name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: "*"
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    name: ${{ matrix.os }} - Go ${{ matrix.go_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      # If you want to matrix build , you can append the following list.
      matrix:
        go_version:
          - 1.18
          - 1.19
          - 1.20
        os:
          - ubuntu-latest
    steps:
    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: |
        make tidy-all
    - name: gofmt
      run: |
        go fmt ./...
    - name: build iocli
      run : |
        cd ./iocli && go build -o /usr/local/bin .

    - name: iocli gen
      run : |
        /usr/local/bin/iocli gen
    - name: Unit Test
      run: |
        make test-all