//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by ioc-go-cli

package http_server

import (
	autowire "github.com/alibaba/IOC-Golang/autowire"
	"github.com/alibaba/IOC-Golang/autowire/singleton"
)

func init() {
	singleton.RegisterStructDescriber(&autowire.StructDescriber{
		Interface: new(HttpServer),
		Factory: func() interface{} {
			return &Impl{}
		},
		ParamFactory: func() interface{} {
			var _ HTTPServerConfigInterface = &HTTPServerConfig{}
			return &HTTPServerConfig{}
		},
		ConstructFunc: func(i interface{}, p interface{}) (interface{}, error) {
			param := p.(HTTPServerConfigInterface)
			impl := i.(*Impl)
			return param.Create(impl)
		},
	})
}

type HTTPServerConfigInterface interface {
	Create(impl *Impl) (*Impl, error)
}
