//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by iocli

package http_server

import (
	autowire "github.com/alibaba/ioc-golang/autowire"
	"github.com/alibaba/ioc-golang/autowire/singleton"
)

func init() {
	singleton.RegisterStructDescriptor(&autowire.StructDescriptor{
		Interface: new(HttpServer),
		Factory: func() interface{} {
			return &Impl{}
		},
		ParamFactory: func() interface{} {
			var _ hTTPServerConfigInterface = &HTTPServerConfig{}
			return &HTTPServerConfig{}
		},
		ConstructFunc: func(i interface{}, p interface{}) (interface{}, error) {
			param := p.(hTTPServerConfigInterface)
			impl := i.(*Impl)
			return param.Create(impl)
		},
	})
}

type hTTPServerConfigInterface interface {
	Create(impl *Impl) (*Impl, error)
}
