// Code generated by iocli, run 'iocli gen' to re-generate

package api

import (
	autowire "github.com/alibaba/ioc-golang/autowire"
	normal "github.com/alibaba/ioc-golang/autowire/normal"
	rpc_client "github.com/alibaba/ioc-golang/extension/autowire/rpc/rpc_client"
)

func init() {
	rpc_client.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &bankServiceIOCRPCClient{}
		},
		TransactionMethodsMap: map[string]string{
			"AddMoney":    "AddMoneyRollout",
			"RemoveMoney": "RemoveMoneyRollout",
		},
	})
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &bankServiceIOCRPCClient_{}
		},
	})
}

type bankServiceIOCRPCClient_ struct {
	GetMoney_           func(id int) int
	AddMoney_           func(id, num int) error
	AddMoneyRollout_    func(id, num int, errMsg string) error
	RemoveMoney_        func(id, num int) error
	RemoveMoneyRollout_ func(id, num int, errMsg string) error
}

func (b *bankServiceIOCRPCClient_) GetMoney(id int) int {
	return b.GetMoney_(id)
}

func (b *bankServiceIOCRPCClient_) AddMoney(id, num int) error {
	return b.AddMoney_(id, num)
}

func (b *bankServiceIOCRPCClient_) AddMoneyRollout(id, num int, errMsg string) error {
	return b.AddMoneyRollout_(id, num, errMsg)
}

func (b *bankServiceIOCRPCClient_) RemoveMoney(id, num int) error {
	return b.RemoveMoney_(id, num)
}

func (b *bankServiceIOCRPCClient_) RemoveMoneyRollout(id, num int, errMsg string) error {
	return b.RemoveMoneyRollout_(id, num, errMsg)
}

type BankServiceIOCRPCClient interface {
	GetMoney(id int) int
	AddMoney(id, num int) error
	AddMoneyRollout(id, num int, errMsg string) error
	RemoveMoney(id, num int) error
	RemoveMoneyRollout(id, num int, errMsg string) error
}

type bankServiceIOCRPCClient struct {
	GetMoney           func(id int) int
	AddMoney           func(id, num int) error
	AddMoneyRollout    func(id, num int, errMsg string) error
	RemoveMoney        func(id, num int) error
	RemoveMoneyRollout func(id, num int, errMsg string) error
}
